version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: user
    networks:
      - cloud-database

networks:
  cloud-database: